spring.application.name=sosfauna-security

## config do banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sosfauna
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# spring.jpa.hibernate-format_sql=true
# spring.sql.init.data-locations=classpath:script.sql
# spring.sql.init.mode=always

## config do JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## Swagger
springdoc.swagger-ui.path=/swagger-ui.html

## config do servidor SMTP (ex: Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sosfaunape@gmail.com
spring.mail.password=ymke okfp yiob tbwa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true